"use client";
import { useMemo, useState } from "react"; import { Flame, Moon, Sun } from "lucide-react";
import { DashboardCards } from "@/components/DashboardCards"; import { DeviceTable } from "@/components/DeviceTable"; import { ExportButton } from "@/components/ExportButton"; import { FileUploader } from "@/components/FileUploader"; import { FiltersBar } from "@/components/FiltersBar"; import { ProgrammingList } from "@/components/ProgrammingList"; import { QCPanel } from "@/components/QCPanel"; import { RoomAccordion } from "@/components/RoomAccordion"; import { Button } from "@/components/ui/button"; import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { mockDevices } from "@/lib/mock-data"; import type { DeviceFilters, EditableField, FireAlarmDevice, WorkbookState } from "@/lib/types";
const nav=["Dashboard","Master Table","Programming View","Room View","QC","Export"] as const; type View=(typeof nav)[number];
export default function Home(){const [view,setView]=useState<View>("Dashboard"); const [dark,setDark]=useState(false); const [state,setState]=useState<WorkbookState>({fileName:"Mock development data",sheetNames:["MASTER BY ROOM"],devices:mockDevices,masterSheetName:"MASTER BY ROOM",loadedAt:new Date().toISOString()}); const [devices,setDevices]=useState<FireAlarmDevice[]>(mockDevices); const [search,setSearch]=useState(""); const [filters,setFilters]=useState<DeviceFilters>({});
const filtered=useMemo(()=>devices.filter(d=>{const q=search.toLowerCase(); const matches=!q||["Device ID","Room No.","Room Name"].some(k=>String(d[k]||"").toLowerCase().includes(q)); const filtered=Object.entries(filters).every(([k,v])=>!v||d[k]===v); return matches&&filtered;}).sort((a,b)=>(a["Device ID"]||"").localeCompare(b["Device ID"]||"",undefined,{numeric:true})),[devices,search,filters]);
function onUpdate(id:string,field:EditableField,value:string){setDevices(prev=>prev.map(d=>d.__rowId===id?{...d,[field]:value}:d));}
function onLoad(next:WorkbookState){setState(next); setDevices(next.devices);} return <main className={dark?"dark":""}><div className="min-h-screen bg-background text-foreground"><aside className="fixed inset-y-0 left-0 hidden w-72 border-r bg-card p-5 lg:block"><div className="mb-8 flex items-center gap-3"><div className="rounded-xl bg-red-600 p-2 text-white"><Flame/></div><div><h1 className="font-bold">Fire Alarm</h1><p className="text-sm text-muted-foreground">Device Manager</p></div></div><nav className="grid gap-2">{nav.map(n=><Button key={n} variant={view===n?"default":"ghost"} className="justify-start" onClick={()=>setView(n)}>{n}</Button>)}</nav><div className="mt-6"><FileUploader onLoad={onLoad}/></div></aside><section className="lg:pl-72"><header className="sticky top-0 z-10 border-b bg-background/90 p-4 backdrop-blur"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-2xl font-bold">{view}</h2><p className="text-sm text-muted-foreground">{state.fileName} · {devices.length} devices · sheets: {state.sheetNames.length}</p></div><div className="flex gap-2"><div className="lg:hidden"><FileUploader onLoad={onLoad}/></div><Button variant="outline" onClick={()=>setDark(!dark)}>{dark?<Sun/>:<Moon/>}</Button></div></div></header><div className="space-y-5 p-4 lg:p-6">{view==="Dashboard"&&<DashboardCards devices={devices}/>} {view==="Master Table"&&<><FiltersBar devices={devices} search={search} setSearch={setSearch} filters={filters} setFilters={setFilters}/><DeviceTable devices={filtered} onUpdate={onUpdate}/></>} {view==="Programming View"&&<ProgrammingList devices={filtered} onUpdate={onUpdate}/>} {view==="Room View"&&<RoomAccordion devices={filtered}/>} {view==="QC"&&<QCPanel devices={devices}/>} {view==="Export"&&<Card><CardHeader><CardTitle>Export updated workbook</CardTitle></CardHeader><CardContent className="space-y-4"><p className="text-muted-foreground">Exports a new Excel file, keeps original workbook sheets when available, updates MASTER BY ROOM, and adds EXPORT_LOG.</p><ExportButton state={state} devices={devices}/></CardContent></Card>}</div></section></div></main>}
