export const en = {
  appName: 'EVO ALLY GOD 911', topbarSubtitle: 'Season 6 Alliance Command', navHome: 'Command', navLogin: 'Login', navProfile: 'Profile', navAdmin: 'Admin', languageEnglish: 'English', languageChinese: '中文',
  allianceStatus: 'Alliance Status', alliancePower: 'Alliance Power', vip18Players: 'VIP 18 Players', seasonStatus: 'Season 6 Status', currentObjective: 'Current Objective', lastUpdated: 'Last Updated', dataMode: 'Data Mode', mockMode: 'Mock fallback active', supabaseMode: 'Supabase ready',
  nextEvents: 'Next Events', eventTitle: 'Event', eventTime: 'Date / Time', importance: 'Importance', preparation: 'Preparation Required', notes: 'Notes',
  announcements: 'Main Orders / Announcements', createdBy: 'Created By', updatedAt: 'Updated At', priority: 'Priority', content: 'Content',
  quickGuides: 'Season 6 Quick Guides', checklist: 'Checklist', category: 'Category',
  rosterSnapshot: 'Roster Snapshot', vipRallyFocus: 'VIP 18 / Rally Lead Focus', rulesReminders: 'Rules and Reminders', supportPlayers: 'Support Players', rallyUse: 'Rally Use',
  player: 'Player', totalPower: 'Total Power', firstSquadPower: 'First Squad', vip: 'VIP', role: 'Role', squadType: 'Squad', heroes: 'Best Heroes', timezone: 'Timezone', availability: 'Availability', vipAsset: 'VIP 18 Rally Asset', rallyLead: 'Rally Lead', defender: 'Defender',
  loginTitle: 'Alliance Login', loginSubtitle: 'Members sign in with Supabase auth. Demo mode stays available when env vars are missing.', email: 'Email', password: 'Password', signIn: 'Sign In', authDemo: 'Auth demo: configure Supabase env vars to enable live login.',
  profileTitle: 'My Profile', profileSubtitle: 'Members can update only their own roster profile. R4/R5 can manage all profiles from Admin.', saveProfile: 'Save Profile',
  adminTitle: 'Admin Command Center', adminSubtitle: 'R4/R5 manage homepage posts, next events, guide cards, rules, roster data, and CSV imports.', adminOnly: 'R4/R5 Admins Only', manageAnnouncements: 'Manage Announcements', manageEvents: 'Manage Events', manageGuides: 'Manage Guides', manageRules: 'Manage Rules', manageRoster: 'Manage Roster', openImport: 'Open CSV Import',
  importTitle: 'Roster CSV Import', importSubtitle: 'Import the initial roster from a Google Sheets CSV export. Validate rows and preview before final import.', expectedFields: 'Expected Fields', importSteps: 'Import Steps', chooseCsv: 'Choose CSV', previewImport: 'Preview Import', finalImport: 'Final Import',
  priorityHigh: 'High', priorityMedium: 'Medium', priorityLow: 'Low', emptyState: 'No active command data yet.', errorState: 'Command data unavailable. Using local fallback.', notFoundTitle: 'Command route not found', notFoundBody: 'Return to the main alliance command dashboard.', returnHome: 'Return Home',
  day: 'Day', title: 'Title', type: 'Type', responsible: 'Responsible', status: 'Status', statusOpen: 'Open', statusInProgress: 'In Progress', statusLocked: 'Locked', statusDone: 'Done', accessGateTitle: 'Restricted Alliance Access', accessGateBody: 'Enable this gate after Supabase auth policies are live.',
  jumpStatus: 'Status', jumpEvents: 'Events', jumpOrders: 'Orders', jumpGuides: 'Guides', jumpRoster: 'Roster', jumpVip: 'VIP 18', jumpRules: 'Rules'
} as const;
